/////////////////////////////////////////////////////////////////////////////
//

$(document).ready(function()
{
$(".s1").click(function() {
   $("div.stena").html("<img src='./img/2/1.png' class='ster'  style='position: absolute;width: 700px;'>");          
})
$(".s2").click(function() {
   $("div.stena").html("<img src='./img/2/3.png' class='ster'  style='position: absolute;width: 700px;'>");          
})
$(".s3").click(function() {
   $("div.stena").html("<img src='./img/2/4.png' class='ster'  style='position: absolute;width: 700px;'>");          
})
$(".s4").click(function() {
   $("div.stena").html("<img src='./img/2/5.png' class='ster'  style='position: absolute;width: 700px;'>");          
})
$(".s5").click(function() {
   $("div.stena").html("<img src='./img/2/2.png' class='ster'  style='position: absolute;width: 700px;'>");          
})


$(".h1").click(function() {
   $("div.izdelie").html("<img src='./img/3/1.png' class='ster'  style='position: absolute;width: 700px;'>");
   $("div.p1").show();
   $("div.p2").hide();
   $("div.p3").hide(); 
   $("div.p4").hide();
   $("div.p5").hide(); 
   $('.box').empty();
   
})
$(".h2").click(function() {
   $("div.izdelie").html("<img src='./img/3/2.png' class='ster'  style='position: absolute;width: 700px;'>");  
$("div.p2").show();
   $("div.p1").hide();
   $("div.p3").hide(); 
   $("div.p4").hide();
   $("div.p5").hide();  
$('.box').empty();   
     
})
$(".h3").click(function() {
   $("div.izdelie").html("<img src='./img/3/3.png' class='ster'  style='position: absolute;width: 700px;'>");
   $("div.p3").show();
   $("div.p2").hide();
   $("div.p1").hide(); 
   $("div.p4").hide();
   $("div.p5").hide();
   $('.box').empty();
   
})
$(".h4").click(function() {
   $("div.izdelie").html("<img src='./img/3/4.png' class='ster'  style='position: absolute;width: 700px;'>");  
   $("div.p4").show();
   $("div.p2").hide();
   $("div.p3").hide(); 
   $("div.p1").hide();
   $("div.p5").hide();
   $('.box').empty();
})
$(".h5").click(function() {
   $("div.izdelie").html("<img src='./img/3/5.png' class='ster'  style='position: absolute;width: 700px;'>");    
  $("div.p5").show();
   $("div.p2").hide();
   $("div.p3").hide(); 
   $("div.p4").hide();
   $("div.p1").hide();
   $('.box').empty();
})


$(".v1").click(function(){$("div.box").html("<img src='./img/main/1/1.png'   style='position: absolute;width: 700px;'>");})
$(".v2").click(function(){$("div.box").html("<img src='./img/main/1/2.png'   style='position: absolute;width: 700px;'>");})
$(".v3").click(function(){$("div.box").html("<img src='./img/main/1/3.png'   style='position: absolute;width: 700px;'>");})
$(".v4").click(function(){$("div.box").html("<img src='./img/main/1/4.png'   style='position: absolute;width: 700px;'>");})
$(".v5").click(function(){$("div.box").html("<img src='./img/main/1/5.png'   style='position: absolute;width: 700px;'>");})
$(".v6").click(function(){$("div.box").html("<img src='./img/main/1/6.png'   style='position: absolute;width: 700px;'>");})
$(".v7").click(function(){$("div.box").html("<img src='./img/main/1/7.png'   style='position: absolute;width: 700px;'>");})
$(".v8").click(function(){$("div.box").html("<img src='./img/main/1/8.png'   style='position: absolute;width: 700px;'>");})
$(".v9").click(function(){$("div.box").html("<img src='./img/main/1/9.png'   style='position: absolute;width: 700px;'>");})
$(".v10").click(function(){$("div.box").html("<img src='./img/main/1/10.png'   style='position: absolute;width: 700px;'>");})
$(".v11").click(function(){$("div.box").html("<img src='./img/main/1/11.png'   style='position: absolute;width: 700px;'>");})
$(".v12").click(function(){$("div.box").html("<img src='./img/main/1/12.png'   style='position: absolute;width: 700px;'>");})
$(".v13").click(function(){$("div.box").html("<img src='./img/main/1/13.png'   style='position: absolute;width: 700px;'>");})
$(".v14").click(function(){$("div.box").html("<img src='./img/main/1/14.png'   style='position: absolute;width: 700px;'>");})
$(".v15").click(function(){$("div.box").html("<img src='./img/main/1/15.png'   style='position: absolute;width: 700px;'>");})
$(".v16").click(function(){$("div.box").html("<img src='./img/main/1/16.png'   style='position: absolute;width: 700px;'>");})
$(".v17").click(function(){$("div.box").html("<img src='./img/main/1/17.png'   style='position: absolute;width: 700px;'>");})
$(".v18").click(function(){$("div.box").html("<img src='./img/main/1/18.png'   style='position: absolute;width: 700px;'>");})
$(".v19").click(function(){$("div.box").html("<img src='./img/main/1/19.png'   style='position: absolute;width: 700px;'>");})
$(".v20").click(function(){$("div.box").html("<img src='./img/main/1/20.png'   style='position: absolute;width: 700px;'>");})
$(".v21").click(function(){$("div.box").html("<img src='./img/main/1/21.png'   style='position: absolute;width: 700px;'>");})
$(".v22").click(function(){$("div.box").html("<img src='./img/main/1/22.png'   style='position: absolute;width: 700px;'>");})
$(".v23").click(function(){$("div.box").html("<img src='./img/main/1/23.png'   style='position: absolute;width: 700px;'>");})
$(".v24").click(function(){$("div.box").html("<img src='./img/main/1/24.png'   style='position: absolute;width: 700px;'>");})
$(".v25").click(function(){$("div.box").html("<img src='./img/main/1/25.png'   style='position: absolute;width: 700px;'>");})
$(".v26").click(function(){$("div.box").html("<img src='./img/main/1/26.png'   style='position: absolute;width: 700px;'>");})
$(".v27").click(function(){$("div.box").html("<img src='./img/main/1/27.png'   style='position: absolute;width: 700px;'>");})
$(".v28").click(function(){$("div.box").html("<img src='./img/main/1/28.png'   style='position: absolute;width: 700px;'>");})
$(".v29").click(function(){$("div.box").html("<img src='./img/main/1/29.png'   style='position: absolute;width: 700px;'>");})
$(".v30").click(function(){$("div.box").html("<img src='./img/main/1/30.png'   style='position: absolute;width: 700px;'>");})
$(".v31").click(function(){$("div.box").html("<img src='./img/main/1/31.png'   style='position: absolute;width: 700px;'>");})
$(".v32").click(function(){$("div.box").html("<img src='./img/main/1/32.png'   style='position: absolute;width: 700px;'>");})
$(".v33").click(function(){$("div.box").html("<img src='./img/main/1/33.png'   style='position: absolute;width: 700px;'>");})
$(".v34").click(function(){$("div.box").html("<img src='./img/main/1/34.png'   style='position: absolute;width: 700px;'>");})
$(".v35").click(function(){$("div.box").html("<img src='./img/main/1/35.png'   style='position: absolute;width: 700px;'>");})
$(".v36").click(function(){$("div.box").html("<img src='./img/main/1/36.png'   style='position: absolute;width: 700px;'>");})
$(".v37").click(function(){$("div.box").html("<img src='./img/main/1/37.png'   style='position: absolute;width: 700px;'>");})
$(".v38").click(function(){$("div.box").html("<img src='./img/main/1/38.png'   style='position: absolute;width: 700px;'>");})
$(".v39").click(function(){$("div.box").html("<img src='./img/main/1/39.png'   style='position: absolute;width: 700px;'>");})
$(".v40").click(function(){$("div.box").html("<img src='./img/main/1/40.png'   style='position: absolute;width: 700px;'>");})
$(".v41").click(function(){$("div.box").html("<img src='./img/main/1/41.png'   style='position: absolute;width: 700px;'>");})
$(".v42").click(function(){$("div.box").html("<img src='./img/main/1/42.png'   style='position: absolute;width: 700px;'>");})
$(".v43").click(function(){$("div.box").html("<img src='./img/main/1/43.png'   style='position: absolute;width: 700px;'>");})
$(".v44").click(function(){$("div.box").html("<img src='./img/main/1/44.png'   style='position: absolute;width: 700px;'>");})
$(".v45").click(function(){$("div.box").html("<img src='./img/main/1/45.png'   style='position: absolute;width: 700px;'>");})
$(".v46").click(function(){$("div.box").html("<img src='./img/main/1/46.png'   style='position: absolute;width: 700px;'>");})
$(".v47").click(function(){$("div.box").html("<img src='./img/main/1/47.png'   style='position: absolute;width: 700px;'>");})
$(".v48").click(function(){$("div.box").html("<img src='./img/main/1/48.png'   style='position: absolute;width: 700px;'>");})
$(".v49").click(function(){$("div.box").html("<img src='./img/main/1/49.png'   style='position: absolute;width: 700px;'>");})
$(".v50").click(function(){$("div.box").html("<img src='./img/main/1/50.png'   style='position: absolute;width: 700px;'>");})
$(".v51").click(function(){$("div.box").html("<img src='./img/main/1/51.png'   style='position: absolute;width: 700px;'>");})
$(".v52").click(function(){$("div.box").html("<img src='./img/main/1/52.png'   style='position: absolute;width: 700px;'>");})
$(".v53").click(function(){$("div.box").html("<img src='./img/main/1/53.png'   style='position: absolute;width: 700px;'>");})
$(".v54").click(function(){$("div.box").html("<img src='./img/main/1/54.png'   style='position: absolute;width: 700px;'>");})
$(".v55").click(function(){$("div.box").html("<img src='./img/main/1/55.png'   style='position: absolute;width: 700px;'>");})
$(".v56").click(function(){$("div.box").html("<img src='./img/main/1/56.png'   style='position: absolute;width: 700px;'>");})
$(".v57").click(function(){$("div.box").html("<img src='./img/main/1/57.png'   style='position: absolute;width: 700px;'>");})
$(".v58").click(function(){$("div.box").html("<img src='./img/main/1/58.png'   style='position: absolute;width: 700px;'>");})
$(".v59").click(function(){$("div.box").html("<img src='./img/main/1/59.png'   style='position: absolute;width: 700px;'>");})
$(".v60").click(function(){$("div.box").html("<img src='./img/main/1/60.png'   style='position: absolute;width: 700px;'>");})
$(".v61").click(function(){$("div.box").html("<img src='./img/main/1/61.png'   style='position: absolute;width: 700px;'>");})
$(".v62").click(function(){$("div.box").html("<img src='./img/main/1/62.png'   style='position: absolute;width: 700px;'>");})
$(".v63").click(function(){$("div.box").html("<img src='./img/main/1/63.png'   style='position: absolute;width: 700px;'>");})
$(".v64").click(function(){$("div.box").html("<img src='./img/main/1/64.png'   style='position: absolute;width: 700px;'>");})
$(".v65").click(function(){$("div.box").html("<img src='./img/main/1/65.png'   style='position: absolute;width: 700px;'>");})
$(".v66").click(function(){$("div.box").html("<img src='./img/main/1/66.png'   style='position: absolute;width: 700px;'>");})
$(".v67").click(function(){$("div.box").html("<img src='./img/main/1/67.png'   style='position: absolute;width: 700px;'>");})
$(".v68").click(function(){$("div.box").html("<img src='./img/main/1/68.png'   style='position: absolute;width: 700px;'>");})
$(".v69").click(function(){$("div.box").html("<img src='./img/main/1/69.png'   style='position: absolute;width: 700px;'>");})
$(".v70").click(function(){$("div.box").html("<img src='./img/main/1/70.png'   style='position: absolute;width: 700px;'>");})
$(".v71").click(function(){$("div.box").html("<img src='./img/main/1/71.png'   style='position: absolute;width: 700px;'>");})
$(".v72").click(function(){$("div.box").html("<img src='./img/main/1/72.png'   style='position: absolute;width: 700px;'>");})
$(".v73").click(function(){$("div.box").html("<img src='./img/main/1/73.png'   style='position: absolute;width: 700px;'>");})
$(".v74").click(function(){$("div.box").html("<img src='./img/main/1/74.png'   style='position: absolute;width: 700px;'>");})
$(".v75").click(function(){$("div.box").html("<img src='./img/main/1/75.png'   style='position: absolute;width: 700px;'>");})
$(".v76").click(function(){$("div.box").html("<img src='./img/main/1/76.png'   style='position: absolute;width: 700px;'>");})
$(".v77").click(function(){$("div.box").html("<img src='./img/main/1/77.png'   style='position: absolute;width: 700px;'>");})
$(".v78").click(function(){$("div.box").html("<img src='./img/main/1/78.png'   style='position: absolute;width: 700px;'>");})
$(".v79").click(function(){$("div.box").html("<img src='./img/main/1/79.png'   style='position: absolute;width: 700px;'>");})
$(".v80").click(function(){$("div.box").html("<img src='./img/main/1/80.png'   style='position: absolute;width: 700px;'>");})
$(".v81").click(function(){$("div.box").html("<img src='./img/main/1/81.png'   style='position: absolute;width: 700px;'>");})
$(".v82").click(function(){$("div.box").html("<img src='./img/main/1/82.png'   style='position: absolute;width: 700px;'>");})
$(".v83").click(function(){$("div.box").html("<img src='./img/main/1/83.png'   style='position: absolute;width: 700px;'>");})
$(".v84").click(function(){$("div.box").html("<img src='./img/main/1/84.png'   style='position: absolute;width: 700px;'>");})
$(".v85").click(function(){$("div.box").html("<img src='./img/main/1/85.png'   style='position: absolute;width: 700px;'>");})
$(".v86").click(function(){$("div.box").html("<img src='./img/main/1/86.png'   style='position: absolute;width: 700px;'>");})
$(".v87").click(function(){$("div.box").html("<img src='./img/main/1/87.png'   style='position: absolute;width: 700px;'>");})
$(".v88").click(function(){$("div.box").html("<img src='./img/main/1/88.png'   style='position: absolute;width: 700px;'>");})
$(".v89").click(function(){$("div.box").html("<img src='./img/main/1/89.png'   style='position: absolute;width: 700px;'>");})
$(".v90").click(function(){$("div.box").html("<img src='./img/main/1/90.png'   style='position: absolute;width: 700px;'>");})
$(".v91").click(function(){$("div.box").html("<img src='./img/main/1/91.png'   style='position: absolute;width: 700px;'>");})
$(".v92").click(function(){$("div.box").html("<img src='./img/main/1/92.png'   style='position: absolute;width: 700px;'>");})
$(".v93").click(function(){$("div.box").html("<img src='./img/main/1/93.png'   style='position: absolute;width: 700px;'>");})
$(".v94").click(function(){$("div.box").html("<img src='./img/main/1/94.png'   style='position: absolute;width: 700px;'>");})
$(".v95").click(function(){$("div.box").html("<img src='./img/main/1/95.png'   style='position: absolute;width: 700px;'>");})
$(".v96").click(function(){$("div.box").html("<img src='./img/main/1/96.png'   style='position: absolute;width: 700px;'>");})
$(".v97").click(function(){$("div.box").html("<img src='./img/main/1/97.png'   style='position: absolute;width: 700px;'>");})
$(".v98").click(function(){$("div.box").html("<img src='./img/main/1/98.png'   style='position: absolute;width: 700px;'>");})
$(".v99").click(function(){$("div.box").html("<img src='./img/main/1/99.png'   style='position: absolute;width: 700px;'>");})
$(".v100").click(function(){$("div.box").html("<img src='./img/main/1/100.png'   style='position: absolute;width: 700px;'>");})
$(".v101").click(function(){$("div.box").html("<img src='./img/main/1/101.png'   style='position: absolute;width: 700px;'>");})
$(".v102").click(function(){$("div.box").html("<img src='./img/main/1/102.png'   style='position: absolute;width: 700px;'>");})
$(".v103").click(function(){$("div.box").html("<img src='./img/main/1/103.png'   style='position: absolute;width: 700px;'>");})
$(".v104").click(function(){$("div.box").html("<img src='./img/main/1/104.png'   style='position: absolute;width: 700px;'>");})
$(".v105").click(function(){$("div.box").html("<img src='./img/main/1/105.png'   style='position: absolute;width: 700px;'>");})
$(".v106").click(function(){$("div.box").html("<img src='./img/main/1/106.png'   style='position: absolute;width: 700px;'>");})
$(".v107").click(function(){$("div.box").html("<img src='./img/main/1/107.png'   style='position: absolute;width: 700px;'>");})
$(".v108").click(function(){$("div.box").html("<img src='./img/main/1/108.png'   style='position: absolute;width: 700px;'>");})
$(".v109").click(function(){$("div.box").html("<img src='./img/main/1/109.png'   style='position: absolute;width: 700px;'>");})
$(".v110").click(function(){$("div.box").html("<img src='./img/main/1/110.png'   style='position: absolute;width: 700px;'>");})
$(".v111").click(function(){$("div.box").html("<img src='./img/main/1/111.png'   style='position: absolute;width: 700px;'>");})
$(".v112").click(function(){$("div.box").html("<img src='./img/main/1/112.png'   style='position: absolute;width: 700px;'>");})
$(".v113").click(function(){$("div.box").html("<img src='./img/main/1/113.png'   style='position: absolute;width: 700px;'>");})
$(".v114").click(function(){$("div.box").html("<img src='./img/main/1/114.png'   style='position: absolute;width: 700px;'>");})
$(".v115").click(function(){$("div.box").html("<img src='./img/main/1/115.png'   style='position: absolute;width: 700px;'>");})
$(".v116").click(function(){$("div.box").html("<img src='./img/main/1/116.png'   style='position: absolute;width: 700px;'>");})
$(".v117").click(function(){$("div.box").html("<img src='./img/main/1/117.png'   style='position: absolute;width: 700px;'>");})
$(".v118").click(function(){$("div.box").html("<img src='./img/main/1/118.png'   style='position: absolute;width: 700px;'>");})
$(".v119").click(function(){$("div.box").html("<img src='./img/main/1/119.png'   style='position: absolute;width: 700px;'>");})
$(".v120").click(function(){$("div.box").html("<img src='./img/main/1/120.png'   style='position: absolute;width: 700px;'>");})
$(".v121").click(function(){$("div.box").html("<img src='./img/main/1/121.png'   style='position: absolute;width: 700px;'>");})
$(".v122").click(function(){$("div.box").html("<img src='./img/main/1/122.png'   style='position: absolute;width: 700px;'>");})
$(".v123").click(function(){$("div.box").html("<img src='./img/main/1/123.png'   style='position: absolute;width: 700px;'>");})
$(".v124").click(function(){$("div.box").html("<img src='./img/main/1/124.png'   style='position: absolute;width: 700px;'>");})
$(".v125").click(function(){$("div.box").html("<img src='./img/main/1/125.png'   style='position: absolute;width: 700px;'>");})
$(".v126").click(function(){$("div.box").html("<img src='./img/main/1/126.png'   style='position: absolute;width: 700px;'>");})
$(".v127").click(function(){$("div.box").html("<img src='./img/main/1/127.png'   style='position: absolute;width: 700px;'>");})
$(".v128").click(function(){$("div.box").html("<img src='./img/main/1/128.png'   style='position: absolute;width: 700px;'>");})
$(".v129").click(function(){$("div.box").html("<img src='./img/main/1/129.png'   style='position: absolute;width: 700px;'>");})
$(".v130").click(function(){$("div.box").html("<img src='./img/main/1/130.png'   style='position: absolute;width: 700px;'>");})
$(".v131").click(function(){$("div.box").html("<img src='./img/main/1/131.png'   style='position: absolute;width: 700px;'>");})
$(".v132").click(function(){$("div.box").html("<img src='./img/main/1/132.png'   style='position: absolute;width: 700px;'>");})
$(".v133").click(function(){$("div.box").html("<img src='./img/main/1/133.png'   style='position: absolute;width: 700px;'>");})
$(".v134").click(function(){$("div.box").html("<img src='./img/main/1/134.png'   style='position: absolute;width: 700px;'>");})
$(".v135").click(function(){$("div.box").html("<img src='./img/main/1/135.png'   style='position: absolute;width: 700px;'>");})
$(".v136").click(function(){$("div.box").html("<img src='./img/main/1/136.png'   style='position: absolute;width: 700px;'>");})
$(".v137").click(function(){$("div.box").html("<img src='./img/main/1/137.png'   style='position: absolute;width: 700px;'>");})
$(".v138").click(function(){$("div.box").html("<img src='./img/main/1/138.png'   style='position: absolute;width: 700px;'>");})
$(".v139").click(function(){$("div.box").html("<img src='./img/main/1/139.png'   style='position: absolute;width: 700px;'>");})
$(".v140").click(function(){$("div.box").html("<img src='./img/main/1/140.png'   style='position: absolute;width: 700px;'>");})
$(".v141").click(function(){$("div.box").html("<img src='./img/main/1/141.png'   style='position: absolute;width: 700px;'>");})
$(".v142").click(function(){$("div.box").html("<img src='./img/main/1/142.png'   style='position: absolute;width: 700px;'>");})
$(".v143").click(function(){$("div.box").html("<img src='./img/main/1/143.png'   style='position: absolute;width: 700px;'>");})
$(".v144").click(function(){$("div.box").html("<img src='./img/main/1/144.png'   style='position: absolute;width: 700px;'>");})
$(".v145").click(function(){$("div.box").html("<img src='./img/main/1/145.png'   style='position: absolute;width: 700px;'>");})
$(".v146").click(function(){$("div.box").html("<img src='./img/main/1/146.png'   style='position: absolute;width: 700px;'>");})
$(".v147").click(function(){$("div.box").html("<img src='./img/main/1/147.png'   style='position: absolute;width: 700px;'>");})
$(".v148").click(function(){$("div.box").html("<img src='./img/main/1/148.png'   style='position: absolute;width: 700px;'>");})
$(".v149").click(function(){$("div.box").html("<img src='./img/main/1/149.png'   style='position: absolute;width: 700px;'>");})
$(".v150").click(function(){$("div.box").html("<img src='./img/main/1/150.png'   style='position: absolute;width: 700px;'>");})


$(".v151").click(function(){$("div.box").html("<img src='./img/main/2/151.png\'   style=' position: absolute;width: 700px;'>");})
$(".v152").click(function(){$("div.box").html("<img src='./img/main/2/152.png\'   style=' position: absolute;width: 700px;'>");})
$(".v153").click(function(){$("div.box").html("<img src='./img/main/2/153.png\'   style=' position: absolute;width: 700px;'>");})
$(".v154").click(function(){$("div.box").html("<img src='./img/main/2/154.png\'   style=' position: absolute;width: 700px;'>");})
$(".v155").click(function(){$("div.box").html("<img src='./img/main/2/155.png\'   style=' position: absolute;width: 700px;'>");})
$(".v156").click(function(){$("div.box").html("<img src='./img/main/2/156.png\'   style=' position: absolute;width: 700px;'>");})
$(".v157").click(function(){$("div.box").html("<img src='./img/main/2/157.png\'   style=' position: absolute;width: 700px;'>");})
$(".v158").click(function(){$("div.box").html("<img src='./img/main/2/158.png\'   style=' position: absolute;width: 700px;'>");})
$(".v159").click(function(){$("div.box").html("<img src='./img/main/2/159.png\'   style=' position: absolute;width: 700px;'>");})
$(".v160").click(function(){$("div.box").html("<img src='./img/main/2/160.png\'   style=' position: absolute;width: 700px;'>");})
$(".v161").click(function(){$("div.box").html("<img src='./img/main/2/161.png\'   style=' position: absolute;width: 700px;'>");})
$(".v162").click(function(){$("div.box").html("<img src='./img/main/2/162.png\'   style=' position: absolute;width: 700px;'>");})
$(".v163").click(function(){$("div.box").html("<img src='./img/main/2/163.png\'   style=' position: absolute;width: 700px;'>");})
$(".v164").click(function(){$("div.box").html("<img src='./img/main/2/164.png\'   style=' position: absolute;width: 700px;'>");})
$(".v165").click(function(){$("div.box").html("<img src='./img/main/2/165.png\'   style=' position: absolute;width: 700px;'>");})
$(".v166").click(function(){$("div.box").html("<img src='./img/main/2/166.png\'   style=' position: absolute;width: 700px;'>");})
$(".v167").click(function(){$("div.box").html("<img src='./img/main/2/167.png\'   style=' position: absolute;width: 700px;'>");})
$(".v168").click(function(){$("div.box").html("<img src='./img/main/2/168.png\'   style=' position: absolute;width: 700px;'>");})
$(".v169").click(function(){$("div.box").html("<img src='./img/main/2/169.png\'   style=' position: absolute;width: 700px;'>");})
$(".v170").click(function(){$("div.box").html("<img src='./img/main/2/170.png\'   style=' position: absolute;width: 700px;'>");})
$(".v171").click(function(){$("div.box").html("<img src='./img/main/2/171.png\'   style=' position: absolute;width: 700px;'>");})
$(".v172").click(function(){$("div.box").html("<img src='./img/main/2/172.png\'   style=' position: absolute;width: 700px;'>");})
$(".v173").click(function(){$("div.box").html("<img src='./img/main/2/173.png\'   style=' position: absolute;width: 700px;'>");})
$(".v174").click(function(){$("div.box").html("<img src='./img/main/2/174.png\'   style=' position: absolute;width: 700px;'>");})
$(".v175").click(function(){$("div.box").html("<img src='./img/main/2/175.png\'   style=' position: absolute;width: 700px;'>");})
$(".v176").click(function(){$("div.box").html("<img src='./img/main/2/176.png\'   style=' position: absolute;width: 700px;'>");})
$(".v177").click(function(){$("div.box").html("<img src='./img/main/2/177.png\'   style=' position: absolute;width: 700px;'>");})
$(".v178").click(function(){$("div.box").html("<img src='./img/main/2/178.png\'   style=' position: absolute;width: 700px;'>");})
$(".v179").click(function(){$("div.box").html("<img src='./img/main/2/179.png\'   style=' position: absolute;width: 700px;'>");})
$(".v180").click(function(){$("div.box").html("<img src='./img/main/2/180.png\'   style=' position: absolute;width: 700px;'>");})
$(".v181").click(function(){$("div.box").html("<img src='./img/main/2/181.png\'   style=' position: absolute;width: 700px;'>");})
$(".v182").click(function(){$("div.box").html("<img src='./img/main/2/182.png\'   style=' position: absolute;width: 700px;'>");})
$(".v183").click(function(){$("div.box").html("<img src='./img/main/2/183.png\'   style=' position: absolute;width: 700px;'>");})
$(".v184").click(function(){$("div.box").html("<img src='./img/main/2/184.png\'   style=' position: absolute;width: 700px;'>");})
$(".v185").click(function(){$("div.box").html("<img src='./img/main/2/185.png\'   style=' position: absolute;width: 700px;'>");})
$(".v186").click(function(){$("div.box").html("<img src='./img/main/2/186.png\'   style=' position: absolute;width: 700px;'>");})
$(".v187").click(function(){$("div.box").html("<img src='./img/main/2/187.png\'   style=' position: absolute;width: 700px;'>");})
$(".v188").click(function(){$("div.box").html("<img src='./img/main/2/188.png\'   style=' position: absolute;width: 700px;'>");})
$(".v189").click(function(){$("div.box").html("<img src='./img/main/2/189.png\'   style=' position: absolute;width: 700px;'>");})
$(".v190").click(function(){$("div.box").html("<img src='./img/main/2/190.png\'   style=' position: absolute;width: 700px;'>");})
$(".v191").click(function(){$("div.box").html("<img src='./img/main/2/191.png\'   style=' position: absolute;width: 700px;'>");})
$(".v192").click(function(){$("div.box").html("<img src='./img/main/2/192.png\'   style=' position: absolute;width: 700px;'>");})
$(".v193").click(function(){$("div.box").html("<img src='./img/main/2/193.png\'   style=' position: absolute;width: 700px;'>");})
$(".v194").click(function(){$("div.box").html("<img src='./img/main/2/194.png\'   style=' position: absolute;width: 700px;'>");})
$(".v195").click(function(){$("div.box").html("<img src='./img/main/2/195.png\'   style=' position: absolute;width: 700px;'>");})
$(".v196").click(function(){$("div.box").html("<img src='./img/main/2/196.png\'   style=' position: absolute;width: 700px;'>");})
$(".v197").click(function(){$("div.box").html("<img src='./img/main/2/197.png\'   style=' position: absolute;width: 700px;'>");})
$(".v198").click(function(){$("div.box").html("<img src='./img/main/2/198.png\'   style=' position: absolute;width: 700px;'>");})
$(".v199").click(function(){$("div.box").html("<img src='./img/main/2/199.png\'   style=' position: absolute;width: 700px;'>");})
$(".v200").click(function(){$("div.box").html("<img src='./img/main/2/200.png\'   style=' position: absolute;width: 700px;'>");})
$(".v201").click(function(){$("div.box").html("<img src='./img/main/2/201.png\'   style=' position: absolute;width: 700px;'>");})
$(".v202").click(function(){$("div.box").html("<img src='./img/main/2/202.png\'   style=' position: absolute;width: 700px;'>");})
$(".v203").click(function(){$("div.box").html("<img src='./img/main/2/203.png\'   style=' position: absolute;width: 700px;'>");})
$(".v204").click(function(){$("div.box").html("<img src='./img/main/2/204.png\'   style=' position: absolute;width: 700px;'>");})
$(".v205").click(function(){$("div.box").html("<img src='./img/main/2/205.png\'   style=' position: absolute;width: 700px;'>");})
$(".v206").click(function(){$("div.box").html("<img src='./img/main/2/206.png\'   style=' position: absolute;width: 700px;'>");})
$(".v207").click(function(){$("div.box").html("<img src='./img/main/2/207.png\'   style=' position: absolute;width: 700px;'>");})
$(".v208").click(function(){$("div.box").html("<img src='./img/main/2/208.png\'   style=' position: absolute;width: 700px;'>");})
$(".v209").click(function(){$("div.box").html("<img src='./img/main/2/209.png\'   style=' position: absolute;width: 700px;'>");})
$(".v210").click(function(){$("div.box").html("<img src='./img/main/2/210.png\'   style=' position: absolute;width: 700px;'>");})
$(".v211").click(function(){$("div.box").html("<img src='./img/main/2/211.png\'   style=' position: absolute;width: 700px;'>");})
$(".v212").click(function(){$("div.box").html("<img src='./img/main/2/212.png\'   style=' position: absolute;width: 700px;'>");})
$(".v213").click(function(){$("div.box").html("<img src='./img/main/2/213.png\'   style=' position: absolute;width: 700px;'>");})
$(".v214").click(function(){$("div.box").html("<img src='./img/main/2/214.png\'   style=' position: absolute;width: 700px;'>");})
$(".v215").click(function(){$("div.box").html("<img src='./img/main/2/215.png\'   style=' position: absolute;width: 700px;'>");})
$(".v216").click(function(){$("div.box").html("<img src='./img/main/2/216.png\'   style=' position: absolute;width: 700px;'>");})
$(".v217").click(function(){$("div.box").html("<img src='./img/main/2/217.png\'   style=' position: absolute;width: 700px;'>");})
$(".v218").click(function(){$("div.box").html("<img src='./img/main/2/218.png\'   style=' position: absolute;width: 700px;'>");})
$(".v219").click(function(){$("div.box").html("<img src='./img/main/2/219.png\'   style=' position: absolute;width: 700px;'>");})
$(".v220").click(function(){$("div.box").html("<img src='./img/main/2/220.png\'   style=' position: absolute;width: 700px;'>");})
$(".v221").click(function(){$("div.box").html("<img src='./img/main/2/221.png\'   style=' position: absolute;width: 700px;'>");})
$(".v222").click(function(){$("div.box").html("<img src='./img/main/2/222.png\'   style=' position: absolute;width: 700px;'>");})
$(".v223").click(function(){$("div.box").html("<img src='./img/main/2/223.png\'   style=' position: absolute;width: 700px;'>");})
$(".v224").click(function(){$("div.box").html("<img src='./img/main/2/224.png\'   style=' position: absolute;width: 700px;'>");})
$(".v225").click(function(){$("div.box").html("<img src='./img/main/2/225.png\'   style=' position: absolute;width: 700px;'>");})
$(".v226").click(function(){$("div.box").html("<img src='./img/main/2/226.png\'   style=' position: absolute;width: 700px;'>");})
$(".v227").click(function(){$("div.box").html("<img src='./img/main/2/227.png\'   style=' position: absolute;width: 700px;'>");})
$(".v228").click(function(){$("div.box").html("<img src='./img/main/2/228.png\'   style=' position: absolute;width: 700px;'>");})
$(".v229").click(function(){$("div.box").html("<img src='./img/main/2/229.png\'   style=' position: absolute;width: 700px;'>");})
$(".v230").click(function(){$("div.box").html("<img src='./img/main/2/230.png\'   style=' position: absolute;width: 700px;'>");})
$(".v231").click(function(){$("div.box").html("<img src='./img/main/2/231.png\'   style=' position: absolute;width: 700px;'>");})
$(".v232").click(function(){$("div.box").html("<img src='./img/main/2/232.png\'   style=' position: absolute;width: 700px;'>");})
$(".v233").click(function(){$("div.box").html("<img src='./img/main/2/233.png\'   style=' position: absolute;width: 700px;'>");})
$(".v234").click(function(){$("div.box").html("<img src='./img/main/2/234.png\'   style=' position: absolute;width: 700px;'>");})
$(".v235").click(function(){$("div.box").html("<img src='./img/main/2/235.png\'   style=' position: absolute;width: 700px;'>");})
$(".v236").click(function(){$("div.box").html("<img src='./img/main/2/236.png\'   style=' position: absolute;width: 700px;'>");})
$(".v237").click(function(){$("div.box").html("<img src='./img/main/2/237.png\'   style=' position: absolute;width: 700px;'>");})
$(".v238").click(function(){$("div.box").html("<img src='./img/main/2/238.png\'   style=' position: absolute;width: 700px;'>");})
$(".v239").click(function(){$("div.box").html("<img src='./img/main/2/239.png\'   style=' position: absolute;width: 700px;'>");})
$(".v240").click(function(){$("div.box").html("<img src='./img/main/2/240.png\'   style=' position: absolute;width: 700px;'>");})
$(".v241").click(function(){$("div.box").html("<img src='./img/main/2/241.png\'   style=' position: absolute;width: 700px;'>");})
$(".v242").click(function(){$("div.box").html("<img src='./img/main/2/242.png\'   style=' position: absolute;width: 700px;'>");})
$(".v243").click(function(){$("div.box").html("<img src='./img/main/2/243.png\'   style=' position: absolute;width: 700px;'>");})
$(".v244").click(function(){$("div.box").html("<img src='./img/main/2/244.png\'   style=' position: absolute;width: 700px;'>");})
$(".v245").click(function(){$("div.box").html("<img src='./img/main/2/245.png\'   style=' position: absolute;width: 700px;'>");})
$(".v246").click(function(){$("div.box").html("<img src='./img/main/2/246.png\'   style=' position: absolute;width: 700px;'>");})
$(".v247").click(function(){$("div.box").html("<img src='./img/main/2/247.png\'   style=' position: absolute;width: 700px;'>");})
$(".v248").click(function(){$("div.box").html("<img src='./img/main/2/248.png\'   style=' position: absolute;width: 700px;'>");})
$(".v249").click(function(){$("div.box").html("<img src='./img/main/2/249.png\'   style=' position: absolute;width: 700px;'>");})
$(".v250").click(function(){$("div.box").html("<img src='./img/main/2/250.png\'   style=' position: absolute;width: 700px;'>");})
$(".v251").click(function(){$("div.box").html("<img src='./img/main/2/251.png\'   style=' position: absolute;width: 700px;'>");})
$(".v252").click(function(){$("div.box").html("<img src='./img/main/2/252.png\'   style=' position: absolute;width: 700px;'>");})
$(".v253").click(function(){$("div.box").html("<img src='./img/main/2/253.png\'   style=' position: absolute;width: 700px;'>");})
$(".v254").click(function(){$("div.box").html("<img src='./img/main/2/254.png\'   style=' position: absolute;width: 700px;'>");})
$(".v255").click(function(){$("div.box").html("<img src='./img/main/2/255.png\'   style=' position: absolute;width: 700px;'>");})
$(".v256").click(function(){$("div.box").html("<img src='./img/main/2/256.png\'   style=' position: absolute;width: 700px;'>");})
$(".v257").click(function(){$("div.box").html("<img src='./img/main/2/257.png\'   style=' position: absolute;width: 700px;'>");})
$(".v258").click(function(){$("div.box").html("<img src='./img/main/2/258.png\'   style=' position: absolute;width: 700px;'>");})
$(".v259").click(function(){$("div.box").html("<img src='./img/main/2/259.png\'   style=' position: absolute;width: 700px;'>");})
$(".v260").click(function(){$("div.box").html("<img src='./img/main/2/260.png\'   style=' position: absolute;width: 700px;'>");})
$(".v261").click(function(){$("div.box").html("<img src='./img/main/2/261.png\'   style=' position: absolute;width: 700px;'>");})
$(".v262").click(function(){$("div.box").html("<img src='./img/main/2/262.png\'   style=' position: absolute;width: 700px;'>");})
$(".v263").click(function(){$("div.box").html("<img src='./img/main/2/263.png\'   style=' position: absolute;width: 700px;'>");})
$(".v264").click(function(){$("div.box").html("<img src='./img/main/2/264.png\'   style=' position: absolute;width: 700px;'>");})
$(".v265").click(function(){$("div.box").html("<img src='./img/main/2/265.png\'   style=' position: absolute;width: 700px;'>");})
$(".v266").click(function(){$("div.box").html("<img src='./img/main/2/266.png\'   style=' position: absolute;width: 700px;'>");})
$(".v267").click(function(){$("div.box").html("<img src='./img/main/2/267.png\'   style=' position: absolute;width: 700px;'>");})
$(".v268").click(function(){$("div.box").html("<img src='./img/main/2/268.png\'   style=' position: absolute;width: 700px;'>");})
$(".v269").click(function(){$("div.box").html("<img src='./img/main/2/269.png\'   style=' position: absolute;width: 700px;'>");})
$(".v270").click(function(){$("div.box").html("<img src='./img/main/2/270.png\'   style=' position: absolute;width: 700px;'>");})
$(".v271").click(function(){$("div.box").html("<img src='./img/main/2/271.png\'   style=' position: absolute;width: 700px;'>");})
$(".v272").click(function(){$("div.box").html("<img src='./img/main/2/272.png\'   style=' position: absolute;width: 700px;'>");})
$(".v273").click(function(){$("div.box").html("<img src='./img/main/2/273.png\'   style=' position: absolute;width: 700px;'>");})
$(".v274").click(function(){$("div.box").html("<img src='./img/main/2/274.png\'   style=' position: absolute;width: 700px;'>");})
$(".v275").click(function(){$("div.box").html("<img src='./img/main/2/275.png\'   style=' position: absolute;width: 700px;'>");})
$(".v276").click(function(){$("div.box").html("<img src='./img/main/2/276.png\'   style=' position: absolute;width: 700px;'>");})
$(".v277").click(function(){$("div.box").html("<img src='./img/main/2/277.png\'   style=' position: absolute;width: 700px;'>");})
$(".v278").click(function(){$("div.box").html("<img src='./img/main/2/278.png\'   style=' position: absolute;width: 700px;'>");})
$(".v279").click(function(){$("div.box").html("<img src='./img/main/2/279.png\'   style=' position: absolute;width: 700px;'>");})
$(".v280").click(function(){$("div.box").html("<img src='./img/main/2/280.png\'   style=' position: absolute;width: 700px;'>");})
$(".v281").click(function(){$("div.box").html("<img src='./img/main/2/281.png\'   style=' position: absolute;width: 700px;'>");})
$(".v282").click(function(){$("div.box").html("<img src='./img/main/2/282.png\'   style=' position: absolute;width: 700px;'>");})
$(".v283").click(function(){$("div.box").html("<img src='./img/main/2/283.png\'   style=' position: absolute;width: 700px;'>");})
$(".v284").click(function(){$("div.box").html("<img src='./img/main/2/284.png\'   style=' position: absolute;width: 700px;'>");})
$(".v285").click(function(){$("div.box").html("<img src='./img/main/2/285.png\'   style=' position: absolute;width: 700px;'>");})
$(".v286").click(function(){$("div.box").html("<img src='./img/main/2/286.png\'   style=' position: absolute;width: 700px;'>");})
$(".v287").click(function(){$("div.box").html("<img src='./img/main/2/287.png\'   style=' position: absolute;width: 700px;'>");})
$(".v288").click(function(){$("div.box").html("<img src='./img/main/2/288.png\'   style=' position: absolute;width: 700px;'>");})
$(".v289").click(function(){$("div.box").html("<img src='./img/main/2/289.png\'   style=' position: absolute;width: 700px;'>");})
$(".v290").click(function(){$("div.box").html("<img src='./img/main/2/290.png\'   style=' position: absolute;width: 700px;'>");})
$(".v291").click(function(){$("div.box").html("<img src='./img/main/2/291.png\'   style=' position: absolute;width: 700px;'>");})
$(".v292").click(function(){$("div.box").html("<img src='./img/main/2/292.png\'   style=' position: absolute;width: 700px;'>");})
$(".v293").click(function(){$("div.box").html("<img src='./img/main/2/293.png\'   style=' position: absolute;width: 700px;'>");})
$(".v294").click(function(){$("div.box").html("<img src='./img/main/2/294.png\'   style=' position: absolute;width: 700px;'>");})
$(".v295").click(function(){$("div.box").html("<img src='./img/main/2/295.png\'   style=' position: absolute;width: 700px;'>");})
$(".v296").click(function(){$("div.box").html("<img src='./img/main/2/296.png\'   style=' position: absolute;width: 700px;'>");})
$(".v297").click(function(){$("div.box").html("<img src='./img/main/2/297.png\'   style=' position: absolute;width: 700px;'>");})
$(".v298").click(function(){$("div.box").html("<img src='./img/main/2/298.png\'   style=' position: absolute;width: 700px;'>");})
$(".v299").click(function(){$("div.box").html("<img src='./img/main/2/299.png\'   style=' position: absolute;width: 700px;'>");})
$(".v300").click(function(){$("div.box").html("<img src='./img/main/2/300.png\'   style=' position: absolute;width: 700px;'>");})
$(".v301").click(function(){$("div.box").html("<img src='./img/main/2/301.png\'   style=' position: absolute;width: 700px;'>");})
$(".v302").click(function(){$("div.box").html("<img src='./img/main/2/302.png\'   style=' position: absolute;width: 700px;'>");})
$(".v303").click(function(){$("div.box").html("<img src='./img/main/2/303.png\'   style=' position: absolute;width: 700px;'>");})
$(".v304").click(function(){$("div.box").html("<img src='./img/main/2/304.png\'   style=' position: absolute;width: 700px;'>");})
$(".v305").click(function(){$("div.box").html("<img src='./img/main/2/305.png\'   style=' position: absolute;width: 700px;'>");})
$(".v306").click(function(){$("div.box").html("<img src='./img/main/2/306.png\'   style=' position: absolute;width: 700px;'>");})
$(".v307").click(function(){$("div.box").html("<img src='./img/main/2/307.png\'   style=' position: absolute;width: 700px;'>");})
$(".v308").click(function(){$("div.box").html("<img src='./img/main/2/308.png\'   style=' position: absolute;width: 700px;'>");})
$(".v309").click(function(){$("div.box").html("<img src='./img/main/2/309.png\'   style=' position: absolute;width: 700px;'>");})
$(".v310").click(function(){$("div.box").html("<img src='./img/main/2/310.png\'   style=' position: absolute;width: 700px;'>");})
$(".v311").click(function(){$("div.box").html("<img src='./img/main/2/311.png\'   style=' position: absolute;width: 700px;'>");})
$(".v312").click(function(){$("div.box").html("<img src='./img/main/2/312.png\'   style=' position: absolute;width: 700px;'>");})
$(".v313").click(function(){$("div.box").html("<img src='./img/main/2/313.png\'   style=' position: absolute;width: 700px;'>");})
$(".v314").click(function(){$("div.box").html("<img src='./img/main/2/314.png\'   style=' position: absolute;width: 700px;'>");})
$(".v315").click(function(){$("div.box").html("<img src='./img/main/2/315.png\'   style=' position: absolute;width: 700px;'>");})
$(".v316").click(function(){$("div.box").html("<img src='./img/main/2/316.png\'   style=' position: absolute;width: 700px;'>");})
$(".v317").click(function(){$("div.box").html("<img src='./img/main/2/317.png\'   style=' position: absolute;width: 700px;'>");})
$(".v318").click(function(){$("div.box").html("<img src='./img/main/2/318.png\'   style=' position: absolute;width: 700px;'>");})
$(".v319").click(function(){$("div.box").html("<img src='./img/main/2/319.png\'   style=' position: absolute;width: 700px;'>");})
$(".v320").click(function(){$("div.box").html("<img src='./img/main/2/320.png\'   style=' position: absolute;width: 700px;'>");})
$(".v321").click(function(){$("div.box").html("<img src='./img/main/2/321.png\'   style=' position: absolute;width: 700px;'>");})
$(".v322").click(function(){$("div.box").html("<img src='./img/main/2/322.png\'   style=' position: absolute;width: 700px;'>");})
$(".v323").click(function(){$("div.box").html("<img src='./img/main/2/323.png\'   style=' position: absolute;width: 700px;'>");})
$(".v324").click(function(){$("div.box").html("<img src='./img/main/2/324.png\'   style=' position: absolute;width: 700px;'>");})
$(".v325").click(function(){$("div.box").html("<img src='./img/main/2/325.png\'   style=' position: absolute;width: 700px;'>");})
$(".v326").click(function(){$("div.box").html("<img src='./img/main/2/326.png\'   style=' position: absolute;width: 700px;'>");})
$(".v327").click(function(){$("div.box").html("<img src='./img/main/2/327.png\'   style=' position: absolute;width: 700px;'>");})
$(".v328").click(function(){$("div.box").html("<img src='./img/main/2/328.png\'   style=' position: absolute;width: 700px;'>");})
$(".v329").click(function(){$("div.box").html("<img src='./img/main/2/329.png\'   style=' position: absolute;width: 700px;'>");})
$(".v330").click(function(){$("div.box").html("<img src='./img/main/2/330.png\'   style=' position: absolute;width: 700px;'>");})
$(".v331").click(function(){$("div.box").html("<img src='./img/main/2/331.png\'   style=' position: absolute;width: 700px;'>");})
$(".v332").click(function(){$("div.box").html("<img src='./img/main/2/332.png\'   style=' position: absolute;width: 700px;'>");})
$(".v333").click(function(){$("div.box").html("<img src='./img/main/2/333.png\'   style=' position: absolute;width: 700px;'>");})
$(".v334").click(function(){$("div.box").html("<img src='./img/main/2/334.png\'   style=' position: absolute;width: 700px;'>");})
$(".v335").click(function(){$("div.box").html("<img src='./img/main/2/335.png\'   style=' position: absolute;width: 700px;'>");})
$(".v336").click(function(){$("div.box").html("<img src='./img/main/2/336.png\'   style=' position: absolute;width: 700px;'>");})
$(".v337").click(function(){$("div.box").html("<img src='./img/main/2/337.png\'   style=' position: absolute;width: 700px;'>");})
$(".v338").click(function(){$("div.box").html("<img src='./img/main/2/338.png\'   style=' position: absolute;width: 700px;'>");})
$(".v339").click(function(){$("div.box").html("<img src='./img/main/2/339.png\'   style=' position: absolute;width: 700px;'>");})
$(".v340").click(function(){$("div.box").html("<img src='./img/main/2/340.png\'   style=' position: absolute;width: 700px;'>");})
$(".v341").click(function(){$("div.box").html("<img src='./img/main/2/341.png\'   style=' position: absolute;width: 700px;'>");})
$(".v342").click(function(){$("div.box").html("<img src='./img/main/2/342.png\'   style=' position: absolute;width: 700px;'>");})
$(".v343").click(function(){$("div.box").html("<img src='./img/main/2/343.png\'   style=' position: absolute;width: 700px;'>");})
$(".v344").click(function(){$("div.box").html("<img src='./img/main/2/344.png\'   style=' position: absolute;width: 700px;'>");})
$(".v345").click(function(){$("div.box").html("<img src='./img/main/2/345.png\'   style=' position: absolute;width: 700px;'>");})
$(".v346").click(function(){$("div.box").html("<img src='./img/main/2/346.png\'   style=' position: absolute;width: 700px;'>");})
$(".v347").click(function(){$("div.box").html("<img src='./img/main/2/347.png\'   style=' position: absolute;width: 700px;'>");})
$(".v348").click(function(){$("div.box").html("<img src='./img/main/2/348.png\'   style=' position: absolute;width: 700px;'>");})
$(".v349").click(function(){$("div.box").html("<img src='./img/main/2/349.png\'   style=' position: absolute;width: 700px;'>");})
$(".v350").click(function(){$("div.box").html("<img src='./img/main/2/350.png\'   style=' position: absolute;width: 700px;'>");})
$(".v351").click(function(){$("div.box").html("<img src='./img/main/2/351.png\'   style=' position: absolute;width: 700px;'>");})
$(".v352").click(function(){$("div.box").html("<img src='./img/main/2/352.png\'   style=' position: absolute;width: 700px;'>");})
$(".v353").click(function(){$("div.box").html("<img src='./img/main/2/353.png\'   style=' position: absolute;width: 700px;'>");})
$(".v354").click(function(){$("div.box").html("<img src='./img/main/2/354.png\'   style=' position: absolute;width: 700px;'>");})
$(".v355").click(function(){$("div.box").html("<img src='./img/main/2/355.png\'   style=' position: absolute;width: 700px;'>");})
$(".v356").click(function(){$("div.box").html("<img src='./img/main/2/356.png\'   style=' position: absolute;width: 700px;'>");})
$(".v357").click(function(){$("div.box").html("<img src='./img/main/2/357.png\'   style=' position: absolute;width: 700px;'>");})
$(".v358").click(function(){$("div.box").html("<img src='./img/main/2/358.png\'   style=' position: absolute;width: 700px;'>");})
$(".v359").click(function(){$("div.box").html("<img src='./img/main/2/359.png\'   style=' position: absolute;width: 700px;'>");})
$(".v360").click(function(){$("div.box").html("<img src='./img/main/2/360.png\'   style=' position: absolute;width: 700px;'>");})
$(".v361").click(function(){$("div.box").html("<img src='./img/main/2/361.png\'   style=' position: absolute;width: 700px;'>");})
$(".v362").click(function(){$("div.box").html("<img src='./img/main/2/362.png\'   style=' position: absolute;width: 700px;'>");})
$(".v363").click(function(){$("div.box").html("<img src='./img/main/2/363.png\'   style=' position: absolute;width: 700px;'>");})
$(".v364").click(function(){$("div.box").html("<img src='./img/main/2/364.png\'   style=' position: absolute;width: 700px;'>");})
$(".v365").click(function(){$("div.box").html("<img src='./img/main/2/365.png\'   style=' position: absolute;width: 700px;'>");})
$(".v366").click(function(){$("div.box").html("<img src='./img/main/2/366.png\'   style=' position: absolute;width: 700px;'>");})
$(".v367").click(function(){$("div.box").html("<img src='./img/main/2/367.png\'   style=' position: absolute;width: 700px;'>");})
$(".v368").click(function(){$("div.box").html("<img src='./img/main/2/368.png\'   style=' position: absolute;width: 700px;'>");})
$(".v369").click(function(){$("div.box").html("<img src='./img/main/2/369.png\'   style=' position: absolute;width: 700px;'>");})
$(".v370").click(function(){$("div.box").html("<img src='./img/main/2/370.png\'   style=' position: absolute;width: 700px;'>");})
$(".v371").click(function(){$("div.box").html("<img src='./img/main/2/371.png\'   style=' position: absolute;width: 700px;'>");})
$(".v372").click(function(){$("div.box").html("<img src='./img/main/2/372.png\'   style=' position: absolute;width: 700px;'>");})
$(".v373").click(function(){$("div.box").html("<img src='./img/main/2/373.png\'   style=' position: absolute;width: 700px;'>");})
$(".v374").click(function(){$("div.box").html("<img src='./img/main/2/374.png\'   style=' position: absolute;width: 700px;'>");})
$(".v375").click(function(){$("div.box").html("<img src='./img/main/2/375.png\'   style=' position: absolute;width: 700px;'>");})
$(".v376").click(function(){$("div.box").html("<img src='./img/main/2/376.png\'   style=' position: absolute;width: 700px;'>");})
$(".v377").click(function(){$("div.box").html("<img src='./img/main/2/377.png\'   style=' position: absolute;width: 700px;'>");})
$(".v378").click(function(){$("div.box").html("<img src='./img/main/2/378.png\'   style=' position: absolute;width: 700px;'>");})
$(".v379").click(function(){$("div.box").html("<img src='./img/main/2/379.png\'   style=' position: absolute;width: 700px;'>");})
$(".v380").click(function(){$("div.box").html("<img src='./img/main/2/380.png\'   style=' position: absolute;width: 700px;'>");})


$(".v381").click(function(){$("div.box").html("<img src='./img/main/3/381.png\'   style=' position: absolute;width: 700px;'>");})
$(".v382").click(function(){$("div.box").html("<img src='./img/main/3/382.png\'   style=' position: absolute;width: 700px;'>");})
$(".v383").click(function(){$("div.box").html("<img src='./img/main/3/383.png\'   style=' position: absolute;width: 700px;'>");})
$(".v384").click(function(){$("div.box").html("<img src='./img/main/3/384.png\'   style=' position: absolute;width: 700px;'>");})
$(".v385").click(function(){$("div.box").html("<img src='./img/main/3/385.png\'   style=' position: absolute;width: 700px;'>");})
$(".v386").click(function(){$("div.box").html("<img src='./img/main/3/386.png\'   style=' position: absolute;width: 700px;'>");})
$(".v387").click(function(){$("div.box").html("<img src='./img/main/3/387.png\'   style=' position: absolute;width: 700px;'>");})
$(".v388").click(function(){$("div.box").html("<img src='./img/main/3/388.png\'   style=' position: absolute;width: 700px;'>");})
$(".v389").click(function(){$("div.box").html("<img src='./img/main/3/389.png\'   style=' position: absolute;width: 700px;'>");})
$(".v390").click(function(){$("div.box").html("<img src='./img/main/3/390.png\'   style=' position: absolute;width: 700px;'>");})
$(".v391").click(function(){$("div.box").html("<img src='./img/main/3/391.png\'   style=' position: absolute;width: 700px;'>");})
$(".v392").click(function(){$("div.box").html("<img src='./img/main/3/392.png\'   style=' position: absolute;width: 700px;'>");})
$(".v393").click(function(){$("div.box").html("<img src='./img/main/3/393.png\'   style=' position: absolute;width: 700px;'>");})
$(".v394").click(function(){$("div.box").html("<img src='./img/main/3/394.png\'   style=' position: absolute;width: 700px;'>");})
$(".v395").click(function(){$("div.box").html("<img src='./img/main/3/395.png\'   style=' position: absolute;width: 700px;'>");})
$(".v396").click(function(){$("div.box").html("<img src='./img/main/3/396.png\'   style=' position: absolute;width: 700px;'>");})
$(".v397").click(function(){$("div.box").html("<img src='./img/main/3/397.png\'   style=' position: absolute;width: 700px;'>");})
$(".v398").click(function(){$("div.box").html("<img src='./img/main/3/398.png\'   style=' position: absolute;width: 700px;'>");})
$(".v399").click(function(){$("div.box").html("<img src='./img/main/3/399.png\'   style=' position: absolute;width: 700px;'>");})
$(".v400").click(function(){$("div.box").html("<img src='./img/main/3/400.png\'   style=' position: absolute;width: 700px;'>");})
$(".v401").click(function(){$("div.box").html("<img src='./img/main/3/401.png\'   style=' position: absolute;width: 700px;'>");})
$(".v402").click(function(){$("div.box").html("<img src='./img/main/3/402.png\'   style=' position: absolute;width: 700px;'>");})
$(".v403").click(function(){$("div.box").html("<img src='./img/main/3/403.png\'   style=' position: absolute;width: 700px;'>");})
$(".v404").click(function(){$("div.box").html("<img src='./img/main/3/404.png\'   style=' position: absolute;width: 700px;'>");})
$(".v405").click(function(){$("div.box").html("<img src='./img/main/3/405.png\'   style=' position: absolute;width: 700px;'>");})
$(".v406").click(function(){$("div.box").html("<img src='./img/main/3/406.png\'   style=' position: absolute;width: 700px;'>");})
$(".v407").click(function(){$("div.box").html("<img src='./img/main/3/407.png\'   style=' position: absolute;width: 700px;'>");})
$(".v408").click(function(){$("div.box").html("<img src='./img/main/3/408.png\'   style=' position: absolute;width: 700px;'>");})
$(".v409").click(function(){$("div.box").html("<img src='./img/main/3/409.png\'   style=' position: absolute;width: 700px;'>");})
$(".v410").click(function(){$("div.box").html("<img src='./img/main/3/410.png\'   style=' position: absolute;width: 700px;'>");})
$(".v411").click(function(){$("div.box").html("<img src='./img/main/3/411.png\'   style=' position: absolute;width: 700px;'>");})
$(".v412").click(function(){$("div.box").html("<img src='./img/main/3/412.png\'   style=' position: absolute;width: 700px;'>");})
$(".v413").click(function(){$("div.box").html("<img src='./img/main/3/413.png\'   style=' position: absolute;width: 700px;'>");})
$(".v414").click(function(){$("div.box").html("<img src='./img/main/3/414.png\'   style=' position: absolute;width: 700px;'>");})
$(".v415").click(function(){$("div.box").html("<img src='./img/main/3/415.png\'   style=' position: absolute;width: 700px;'>");})
$(".v416").click(function(){$("div.box").html("<img src='./img/main/3/416.png\'   style=' position: absolute;width: 700px;'>");})
$(".v417").click(function(){$("div.box").html("<img src='./img/main/3/417.png\'   style=' position: absolute;width: 700px;'>");})
$(".v418").click(function(){$("div.box").html("<img src='./img/main/3/418.png\'   style=' position: absolute;width: 700px;'>");})
$(".v419").click(function(){$("div.box").html("<img src='./img/main/3/419.png\'   style=' position: absolute;width: 700px;'>");})
$(".v420").click(function(){$("div.box").html("<img src='./img/main/3/420.png\'   style=' position: absolute;width: 700px;'>");})
$(".v421").click(function(){$("div.box").html("<img src='./img/main/3/421.png\'   style=' position: absolute;width: 700px;'>");})
$(".v422").click(function(){$("div.box").html("<img src='./img/main/3/422.png\'   style=' position: absolute;width: 700px;'>");})
$(".v423").click(function(){$("div.box").html("<img src='./img/main/3/423.png\'   style=' position: absolute;width: 700px;'>");})
$(".v424").click(function(){$("div.box").html("<img src='./img/main/3/424.png\'   style=' position: absolute;width: 700px;'>");})
$(".v425").click(function(){$("div.box").html("<img src='./img/main/3/425.png\'   style=' position: absolute;width: 700px;'>");})
$(".v426").click(function(){$("div.box").html("<img src='./img/main/3/426.png\'   style=' position: absolute;width: 700px;'>");})
$(".v427").click(function(){$("div.box").html("<img src='./img/main/3/427.png\'   style=' position: absolute;width: 700px;'>");})
$(".v428").click(function(){$("div.box").html("<img src='./img/main/3/428.png\'   style=' position: absolute;width: 700px;'>");})
$(".v429").click(function(){$("div.box").html("<img src='./img/main/3/429.png\'   style=' position: absolute;width: 700px;'>");})
$(".v430").click(function(){$("div.box").html("<img src='./img/main/3/430.png\'   style=' position: absolute;width: 700px;'>");})
$(".v431").click(function(){$("div.box").html("<img src='./img/main/3/431.png\'   style=' position: absolute;width: 700px;'>");})
$(".v432").click(function(){$("div.box").html("<img src='./img/main/3/432.png\'   style=' position: absolute;width: 700px;'>");})
$(".v433").click(function(){$("div.box").html("<img src='./img/main/3/433.png\'   style=' position: absolute;width: 700px;'>");})
$(".v434").click(function(){$("div.box").html("<img src='./img/main/3/434.png\'   style=' position: absolute;width: 700px;'>");})
$(".v435").click(function(){$("div.box").html("<img src='./img/main/3/435.png\'   style=' position: absolute;width: 700px;'>");})
$(".v436").click(function(){$("div.box").html("<img src='./img/main/3/436.png\'   style=' position: absolute;width: 700px;'>");})
$(".v437").click(function(){$("div.box").html("<img src='./img/main/3/437.png\'   style=' position: absolute;width: 700px;'>");})


$(".v438").click(function(){$("div.box").html("<img src='./img/main/4/438.png\'   style=' position: absolute;width: 700px;'>");})
$(".v439").click(function(){$("div.box").html("<img src='./img/main/4/439.png\'   style=' position: absolute;width: 700px;'>");})
$(".v440").click(function(){$("div.box").html("<img src='./img/main/4/440.png\'   style=' position: absolute;width: 700px;'>");})
$(".v441").click(function(){$("div.box").html("<img src='./img/main/4/441.png\'   style=' position: absolute;width: 700px;'>");})
$(".v442").click(function(){$("div.box").html("<img src='./img/main/4/442.png\'   style=' position: absolute;width: 700px;'>");})
$(".v443").click(function(){$("div.box").html("<img src='./img/main/4/443.png\'   style=' position: absolute;width: 700px;'>");})
$(".v444").click(function(){$("div.box").html("<img src='./img/main/4/444.png\'   style=' position: absolute;width: 700px;'>");})
$(".v445").click(function(){$("div.box").html("<img src='./img/main/4/445.png\'   style=' position: absolute;width: 700px;'>");})
$(".v446").click(function(){$("div.box").html("<img src='./img/main/4/446.png\'   style=' position: absolute;width: 700px;'>");})
$(".v447").click(function(){$("div.box").html("<img src='./img/main/4/447.png\'   style=' position: absolute;width: 700px;'>");})
$(".v448").click(function(){$("div.box").html("<img src='./img/main/4/448.png\'   style=' position: absolute;width: 700px;'>");})
$(".v449").click(function(){$("div.box").html("<img src='./img/main/4/449.png\'   style=' position: absolute;width: 700px;'>");})
$(".v450").click(function(){$("div.box").html("<img src='./img/main/4/450.png\'   style=' position: absolute;width: 700px;'>");})
$(".v451").click(function(){$("div.box").html("<img src='./img/main/4/451.png\'   style=' position: absolute;width: 700px;'>");})
$(".v452").click(function(){$("div.box").html("<img src='./img/main/4/452.png\'   style=' position: absolute;width: 700px;'>");})
$(".v453").click(function(){$("div.box").html("<img src='./img/main/4/453.png\'   style=' position: absolute;width: 700px;'>");})
$(".v454").click(function(){$("div.box").html("<img src='./img/main/4/454.png\'   style=' position: absolute;width: 700px;'>");})
$(".v455").click(function(){$("div.box").html("<img src='./img/main/4/455.png\'   style=' position: absolute;width: 700px;'>");})
$(".v456").click(function(){$("div.box").html("<img src='./img/main/4/456.png\'   style=' position: absolute;width: 700px;'>");})
$(".v457").click(function(){$("div.box").html("<img src='./img/main/4/457.png\'   style=' position: absolute;width: 700px;'>");})
$(".v458").click(function(){$("div.box").html("<img src='./img/main/4/458.png\'   style=' position: absolute;width: 700px;'>");})
$(".v459").click(function(){$("div.box").html("<img src='./img/main/4/459.png\'   style=' position: absolute;width: 700px;'>");})
$(".v460").click(function(){$("div.box").html("<img src='./img/main/4/460.png\'   style=' position: absolute;width: 700px;'>");})
$(".v461").click(function(){$("div.box").html("<img src='./img/main/4/461.png\'   style=' position: absolute;width: 700px;'>");})
$(".v462").click(function(){$("div.box").html("<img src='./img/main/4/462.png\'   style=' position: absolute;width: 700px;'>");})
$(".v463").click(function(){$("div.box").html("<img src='./img/main/4/463.png\'   style=' position: absolute;width: 700px;'>");})
$(".v464").click(function(){$("div.box").html("<img src='./img/main/4/464.png\'   style=' position: absolute;width: 700px;'>");})
$(".v465").click(function(){$("div.box").html("<img src='./img/main/4/465.png\'   style=' position: absolute;width: 700px;'>");})
$(".v466").click(function(){$("div.box").html("<img src='./img/main/4/466.png\'   style=' position: absolute;width: 700px;'>");})
$(".v467").click(function(){$("div.box").html("<img src='./img/main/4/467.png\'   style=' position: absolute;width: 700px;'>");})
$(".v468").click(function(){$("div.box").html("<img src='./img/main/4/468.png\'   style=' position: absolute;width: 700px;'>");})
$(".v469").click(function(){$("div.box").html("<img src='./img/main/4/469.png\'   style=' position: absolute;width: 700px;'>");})
$(".v470").click(function(){$("div.box").html("<img src='./img/main/4/470.png\'   style=' position: absolute;width: 700px;'>");})
$(".v471").click(function(){$("div.box").html("<img src='./img/main/4/471.png\'   style=' position: absolute;width: 700px;'>");})
$(".v472").click(function(){$("div.box").html("<img src='./img/main/4/472.png\'   style=' position: absolute;width: 700px;'>");})
$(".v473").click(function(){$("div.box").html("<img src='./img/main/4/473.png\'   style=' position: absolute;width: 700px;'>");})
$(".v474").click(function(){$("div.box").html("<img src='./img/main/4/474.png\'   style=' position: absolute;width: 700px;'>");})
$(".v475").click(function(){$("div.box").html("<img src='./img/main/4/475.png\'   style=' position: absolute;width: 700px;'>");})
$(".v476").click(function(){$("div.box").html("<img src='./img/main/4/476.png\'   style=' position: absolute;width: 700px;'>");})
$(".v477").click(function(){$("div.box").html("<img src='./img/main/4/477.png\'   style=' position: absolute;width: 700px;'>");})
$(".v478").click(function(){$("div.box").html("<img src='./img/main/4/478.png\'   style=' position: absolute;width: 700px;'>");})
$(".v479").click(function(){$("div.box").html("<img src='./img/main/4/479.png\'   style=' position: absolute;width: 700px;'>");})
$(".v480").click(function(){$("div.box").html("<img src='./img/main/4/480.png\'   style=' position: absolute;width: 700px;'>");})
$(".v481").click(function(){$("div.box").html("<img src='./img/main/4/481.png\'   style=' position: absolute;width: 700px;'>");})
$(".v482").click(function(){$("div.box").html("<img src='./img/main/4/482.png\'   style=' position: absolute;width: 700px;'>");})
$(".v483").click(function(){$("div.box").html("<img src='./img/main/4/483.png\'   style=' position: absolute;width: 700px;'>");})
$(".v484").click(function(){$("div.box").html("<img src='./img/main/4/484.png\'   style=' position: absolute;width: 700px;'>");})
$(".v485").click(function(){$("div.box").html("<img src='./img/main/4/485.png\'   style=' position: absolute;width: 700px;'>");})
$(".v486").click(function(){$("div.box").html("<img src='./img/main/4/486.png\'   style=' position: absolute;width: 700px;'>");})
$(".v487").click(function(){$("div.box").html("<img src='./img/main/4/487.png\'   style=' position: absolute;width: 700px;'>");})
$(".v488").click(function(){$("div.box").html("<img src='./img/main/4/488.png\'   style=' position: absolute;width: 700px;'>");})
$(".v489").click(function(){$("div.box").html("<img src='./img/main/4/489.png\'   style=' position: absolute;width: 700px;'>");})
$(".v490").click(function(){$("div.box").html("<img src='./img/main/4/490.png\'   style=' position: absolute;width: 700px;'>");})
$(".v491").click(function(){$("div.box").html("<img src='./img/main/4/491.png\'   style=' position: absolute;width: 700px;'>");})
$(".v492").click(function(){$("div.box").html("<img src='./img/main/4/492.png\'   style=' position: absolute;width: 700px;'>");})
$(".v493").click(function(){$("div.box").html("<img src='./img/main/4/493.png\'   style=' position: absolute;width: 700px;'>");})
$(".v494").click(function(){$("div.box").html("<img src='./img/main/4/494.png\'   style=' position: absolute;width: 700px;'>");})
$(".v495").click(function(){$("div.box").html("<img src='./img/main/4/495.png\'   style=' position: absolute;width: 700px;'>");})
$(".v496").click(function(){$("div.box").html("<img src='./img/main/4/496.png\'   style=' position: absolute;width: 700px;'>");})
$(".v497").click(function(){$("div.box").html("<img src='./img/main/4/497.png\'   style=' position: absolute;width: 700px;'>");})
$(".v498").click(function(){$("div.box").html("<img src='./img/main/4/498.png\'   style=' position: absolute;width: 700px;'>");})
$(".v499").click(function(){$("div.box").html("<img src='./img/main/4/499.png\'   style=' position: absolute;width: 700px;'>");})
$(".v500").click(function(){$("div.box").html("<img src='./img/main/4/500.png\'   style=' position: absolute;width: 700px;'>");})
$(".v501").click(function(){$("div.box").html("<img src='./img/main/4/501.png\'   style=' position: absolute;width: 700px;'>");})
$(".v502").click(function(){$("div.box").html("<img src='./img/main/4/502.png\'   style=' position: absolute;width: 700px;'>");})
$(".v503").click(function(){$("div.box").html("<img src='./img/main/4/503.png\'   style=' position: absolute;width: 700px;'>");})
$(".v504").click(function(){$("div.box").html("<img src='./img/main/4/504.png\'   style=' position: absolute;width: 700px;'>");})
$(".v505").click(function(){$("div.box").html("<img src='./img/main/4/505.png\'   style=' position: absolute;width: 700px;'>");})
$(".v506").click(function(){$("div.box").html("<img src='./img/main/4/506.png\'   style=' position: absolute;width: 700px;'>");})
$(".v507").click(function(){$("div.box").html("<img src='./img/main/4/507.png\'   style=' position: absolute;width: 700px;'>");})
$(".v508").click(function(){$("div.box").html("<img src='./img/main/4/508.png\'   style=' position: absolute;width: 700px;'>");})
$(".v509").click(function(){$("div.box").html("<img src='./img/main/4/509.png\'   style=' position: absolute;width: 700px;'>");})
$(".v510").click(function(){$("div.box").html("<img src='./img/main/4/510.png\'   style=' position: absolute;width: 700px;'>");})
$(".v511").click(function(){$("div.box").html("<img src='./img/main/4/511.png\'   style=' position: absolute;width: 700px;'>");})
$(".v512").click(function(){$("div.box").html("<img src='./img/main/4/512.png\'   style=' position: absolute;width: 700px;'>");})
$(".v513").click(function(){$("div.box").html("<img src='./img/main/4/513.png\'   style=' position: absolute;width: 700px;'>");})
$(".v514").click(function(){$("div.box").html("<img src='./img/main/4/514.png\'   style=' position: absolute;width: 700px;'>");})
$(".v515").click(function(){$("div.box").html("<img src='./img/main/4/515.png\'   style=' position: absolute;width: 700px;'>");})
$(".v516").click(function(){$("div.box").html("<img src='./img/main/4/516.png\'   style=' position: absolute;width: 700px;'>");})
$(".v517").click(function(){$("div.box").html("<img src='./img/main/4/517.png\'   style=' position: absolute;width: 700px;'>");})
$(".v518").click(function(){$("div.box").html("<img src='./img/main/4/518.png\'   style=' position: absolute;width: 700px;'>");})
$(".v519").click(function(){$("div.box").html("<img src='./img/main/4/519.png\'   style=' position: absolute;width: 700px;'>");})
$(".v520").click(function(){$("div.box").html("<img src='./img/main/4/520.png\'   style=' position: absolute;width: 700px;'>");})
$(".v521").click(function(){$("div.box").html("<img src='./img/main/4/521.png\'   style=' position: absolute;width: 700px;'>");})
$(".v522").click(function(){$("div.box").html("<img src='./img/main/4/522.png\'   style=' position: absolute;width: 700px;'>");})
$(".v523").click(function(){$("div.box").html("<img src='./img/main/4/523.png\'   style=' position: absolute;width: 700px;'>");})
$(".v524").click(function(){$("div.box").html("<img src='./img/main/4/524.png\'   style=' position: absolute;width: 700px;'>");})
$(".v525").click(function(){$("div.box").html("<img src='./img/main/4/525.png\'   style=' position: absolute;width: 700px;'>");})
$(".v526").click(function(){$("div.box").html("<img src='./img/main/4/526.png\'   style=' position: absolute;width: 700px;'>");})
$(".v527").click(function(){$("div.box").html("<img src='./img/main/4/527.png\'   style=' position: absolute;width: 700px;'>");})
$(".v528").click(function(){$("div.box").html("<img src='./img/main/4/528.png\'   style=' position: absolute;width: 700px;'>");})
$(".v529").click(function(){$("div.box").html("<img src='./img/main/4/529.png\'   style=' position: absolute;width: 700px;'>");})
$(".v530").click(function(){$("div.box").html("<img src='./img/main/4/530.png\'   style=' position: absolute;width: 700px;'>");})
$(".v531").click(function(){$("div.box").html("<img src='./img/main/4/531.png\'   style=' position: absolute;width: 700px;'>");})
$(".v532").click(function(){$("div.box").html("<img src='./img/main/4/532.png\'   style=' position: absolute;width: 700px;'>");})
$(".v533").click(function(){$("div.box").html("<img src='./img/main/4/533.png\'   style=' position: absolute;width: 700px;'>");})
$(".v534").click(function(){$("div.box").html("<img src='./img/main/4/534.png\'   style=' position: absolute;width: 700px;'>");})
$(".v535").click(function(){$("div.box").html("<img src='./img/main/4/535.png\'   style=' position: absolute;width: 700px;'>");})
$(".v536").click(function(){$("div.box").html("<img src='./img/main/4/536.png\'   style=' position: absolute;width: 700px;'>");})
$(".v537").click(function(){$("div.box").html("<img src='./img/main/4/537.png\'   style=' position: absolute;width: 700px;'>");})
$(".v538").click(function(){$("div.box").html("<img src='./img/main/4/538.png\'   style=' position: absolute;width: 700px;'>");})
$(".v539").click(function(){$("div.box").html("<img src='./img/main/4/539.png\'   style=' position: absolute;width: 700px;'>");})
$(".v540").click(function(){$("div.box").html("<img src='./img/main/4/540.png\'   style=' position: absolute;width: 700px;'>");})
$(".v541").click(function(){$("div.box").html("<img src='./img/main/4/541.png\'   style=' position: absolute;width: 700px;'>");})
$(".v542").click(function(){$("div.box").html("<img src='./img/main/4/542.png\'   style=' position: absolute;width: 700px;'>");})
$(".v543").click(function(){$("div.box").html("<img src='./img/main/4/543.png\'   style=' position: absolute;width: 700px;'>");})
$(".v544").click(function(){$("div.box").html("<img src='./img/main/4/544.png\'   style=' position: absolute;width: 700px;'>");})
$(".v545").click(function(){$("div.box").html("<img src='./img/main/4/545.png\'   style=' position: absolute;width: 700px;'>");})
$(".v546").click(function(){$("div.box").html("<img src='./img/main/4/546.png\'   style=' position: absolute;width: 700px;'>");})
$(".v547").click(function(){$("div.box").html("<img src='./img/main/4/547.png\'   style=' position: absolute;width: 700px;'>");})
$(".v548").click(function(){$("div.box").html("<img src='./img/main/4/548.png\'   style=' position: absolute;width: 700px;'>");})
$(".v549").click(function(){$("div.box").html("<img src='./img/main/4/549.png\'   style=' position: absolute;width: 700px;'>");})
$(".v550").click(function(){$("div.box").html("<img src='./img/main/4/550.png\'   style=' position: absolute;width: 700px;'>");})
$(".v551").click(function(){$("div.box").html("<img src='./img/main/4/551.png\'   style=' position: absolute;width: 700px;'>");})
$(".v552").click(function(){$("div.box").html("<img src='./img/main/4/552.png\'   style=' position: absolute;width: 700px;'>");})
$(".v553").click(function(){$("div.box").html("<img src='./img/main/4/553.png\'   style=' position: absolute;width: 700px;'>");})
$(".v554").click(function(){$("div.box").html("<img src='./img/main/4/554.png\'   style=' position: absolute;width: 700px;'>");})
$(".v555").click(function(){$("div.box").html("<img src='./img/main/4/555.png\'   style=' position: absolute;width: 700px;'>");})
$(".v556").click(function(){$("div.box").html("<img src='./img/main/4/556.png\'   style=' position: absolute;width: 700px;'>");})
$(".v557").click(function(){$("div.box").html("<img src='./img/main/4/557.png\'   style=' position: absolute;width: 700px;'>");})
$(".v558").click(function(){$("div.box").html("<img src='./img/main/4/558.png\'   style=' position: absolute;width: 700px;'>");})
$(".v559").click(function(){$("div.box").html("<img src='./img/main/4/559.png\'   style=' position: absolute;width: 700px;'>");})
$(".v560").click(function(){$("div.box").html("<img src='./img/main/4/560.png\'   style=' position: absolute;width: 700px;'>");})
$(".v561").click(function(){$("div.box").html("<img src='./img/main/4/561.png\'   style=' position: absolute;width: 700px;'>");})
$(".v562").click(function(){$("div.box").html("<img src='./img/main/4/562.png\'   style=' position: absolute;width: 700px;'>");})
$(".v563").click(function(){$("div.box").html("<img src='./img/main/4/563.png\'   style=' position: absolute;width: 700px;'>");})
$(".v564").click(function(){$("div.box").html("<img src='./img/main/4/564.png\'   style=' position: absolute;width: 700px;'>");})
$(".v565").click(function(){$("div.box").html("<img src='./img/main/4/565.png\'   style=' position: absolute;width: 700px;'>");})
$(".v566").click(function(){$("div.box").html("<img src='./img/main/4/566.png\'   style=' position: absolute;width: 700px;'>");})
$(".v567").click(function(){$("div.box").html("<img src='./img/main/4/567.png\'   style=' position: absolute;width: 700px;'>");})
$(".v568").click(function(){$("div.box").html("<img src='./img/main/4/568.png\'   style=' position: absolute;width: 700px;'>");})
$(".v569").click(function(){$("div.box").html("<img src='./img/main/4/569.png\'   style=' position: absolute;width: 700px;'>");})
$(".v570").click(function(){$("div.box").html("<img src='./img/main/4/570.png\'   style=' position: absolute;width: 700px;'>");})
$(".v571").click(function(){$("div.box").html("<img src='./img/main/4/571.png\'   style=' position: absolute;width: 700px;'>");})
$(".v572").click(function(){$("div.box").html("<img src='./img/main/4/572.png\'   style=' position: absolute;width: 700px;'>");})
$(".v573").click(function(){$("div.box").html("<img src='./img/main/4/573.png\'   style=' position: absolute;width: 700px;'>");})
$(".v574").click(function(){$("div.box").html("<img src='./img/main/4/574.png\'   style=' position: absolute;width: 700px;'>");})
$(".v575").click(function(){$("div.box").html("<img src='./img/main/4/575.png\'   style=' position: absolute;width: 700px;'>");})
$(".v576").click(function(){$("div.box").html("<img src='./img/main/4/576.png\'   style=' position: absolute;width: 700px;'>");})
$(".v577").click(function(){$("div.box").html("<img src='./img/main/4/577.png\'   style=' position: absolute;width: 700px;'>");})
$(".v578").click(function(){$("div.box").html("<img src='./img/main/4/578.png\'   style=' position: absolute;width: 700px;'>");})
$(".v579").click(function(){$("div.box").html("<img src='./img/main/4/579.png\'   style=' position: absolute;width: 700px;'>");})
$(".v580").click(function(){$("div.box").html("<img src='./img/main/4/580.png\'   style=' position: absolute;width: 700px;'>");})
$(".v581").click(function(){$("div.box").html("<img src='./img/main/4/581.png\'   style=' position: absolute;width: 700px;'>");})
$(".v582").click(function(){$("div.box").html("<img src='./img/main/4/582.png\'   style=' position: absolute;width: 700px;'>");})
$(".v583").click(function(){$("div.box").html("<img src='./img/main/4/583.png\'   style=' position: absolute;width: 700px;'>");})
$(".v584").click(function(){$("div.box").html("<img src='./img/main/4/584.png\'   style=' position: absolute;width: 700px;'>");})
$(".v585").click(function(){$("div.box").html("<img src='./img/main/4/585.png\'   style=' position: absolute;width: 700px;'>");})
$(".v586").click(function(){$("div.box").html("<img src='./img/main/4/586.png\'   style=' position: absolute;width: 700px;'>");})


$(".v587").click(function(){$("div.box").html("<img src='./img/main/5/587.png\'   style=' position: absolute;width: 700px;'>");})
$(".v588").click(function(){$("div.box").html("<img src='./img/main/5/588.png\'   style=' position: absolute;width: 700px;'>");})
$(".v589").click(function(){$("div.box").html("<img src='./img/main/5/589.png\'   style=' position: absolute;width: 700px;'>");})
$(".v590").click(function(){$("div.box").html("<img src='./img/main/5/590.png\'   style=' position: absolute;width: 700px;'>");})
$(".v591").click(function(){$("div.box").html("<img src='./img/main/5/591.png\'   style=' position: absolute;width: 700px;'>");})
$(".v592").click(function(){$("div.box").html("<img src='./img/main/5/592.png\'   style=' position: absolute;width: 700px;'>");})
$(".v593").click(function(){$("div.box").html("<img src='./img/main/5/593.png\'   style=' position: absolute;width: 700px;'>");})
$(".v594").click(function(){$("div.box").html("<img src='./img/main/5/594.png\'   style=' position: absolute;width: 700px;'>");})
$(".v595").click(function(){$("div.box").html("<img src='./img/main/5/595.png\'   style=' position: absolute;width: 700px;'>");})
$(".v596").click(function(){$("div.box").html("<img src='./img/main/5/596.png\'   style=' position: absolute;width: 700px;'>");})
$(".v597").click(function(){$("div.box").html("<img src='./img/main/5/597.png\'   style=' position: absolute;width: 700px;'>");})
$(".v598").click(function(){$("div.box").html("<img src='./img/main/5/598.png\'   style=' position: absolute;width: 700px;'>");})
$(".v599").click(function(){$("div.box").html("<img src='./img/main/5/599.png\'   style=' position: absolute;width: 700px;'>");})
$(".v600").click(function(){$("div.box").html("<img src='./img/main/5/600.png\'   style=' position: absolute;width: 700px;'>");})
$(".v601").click(function(){$("div.box").html("<img src='./img/main/5/601.png\'   style=' position: absolute;width: 700px;'>");})
$(".v602").click(function(){$("div.box").html("<img src='./img/main/5/602.png\'   style=' position: absolute;width: 700px;'>");})
$(".v603").click(function(){$("div.box").html("<img src='./img/main/5/603.png\'   style=' position: absolute;width: 700px;'>");})
$(".v604").click(function(){$("div.box").html("<img src='./img/main/5/604.png\'   style=' position: absolute;width: 700px;'>");})
$(".v605").click(function(){$("div.box").html("<img src='./img/main/5/605.png\'   style=' position: absolute;width: 700px;'>");})
$(".v606").click(function(){$("div.box").html("<img src='./img/main/5/606.png\'   style=' position: absolute;width: 700px;'>");})
$(".v607").click(function(){$("div.box").html("<img src='./img/main/5/607.png\'   style=' position: absolute;width: 700px;'>");})
$(".v608").click(function(){$("div.box").html("<img src='./img/main/5/608.png\'   style=' position: absolute;width: 700px;'>");})
$(".v609").click(function(){$("div.box").html("<img src='./img/main/5/609.png\'   style=' position: absolute;width: 700px;'>");})
	
});